### ISSUE TITLE
App stops (dis)charging for no apparent reason

### ISSUE THREAD

**Issue by rhpijnacker** [V2G-liberty/addon-v2g-liberty#164]
Regularly I see that V2G-Liberty stops (dis)charging in the middle of a session, or with less power.
I added some logging that demonstrates this.
[appdaemon_main.log](https://github.com/user-attachments/files/17756595/appdaemon_main.log)

**Comment by ArdJonker** [comment]
In the log it seems. that the 0 or "lower than max power" values come from the schedule. In the schedule this nearly always only is the first entry where the other values are min/max/zero power values.
So the problem seems to be in the generation of the schedule.

An other thing that i noticed is that the the logfile the relatively high frequency with which new schedule's are requested, more than every 5 min. or so where i would expect every 15 min. This is due to the fast rate of charging (every soc change triggers a new schedule request).

**Comment by rhpijnacker** [comment]
> So the problem seems to be in the generation of the schedule.

Why would the schedule generate values like that? That seems to be a bug in the scheduler then.

> An other thing that i noticed is that the the logfile the relatively high frequency with which new schedule's are requested, more than every 5 min. or so where i would expect every 15 min. This is due to the fast rate of charging (every soc change triggers a new schedule request).

Any idea why this is so much higher for me than usual? If this frequence is considered too high, then maybe requesting a new schedule every time the SoC changes is not a good choice?

**Comment by ArdJonker** [comment]
> Why would the schedule generate values like that? That seems to be a bug in the scheduler then.

There indeed seems to be unwanted behaviour.

> Any idea why this is so much higher for me than usual? If this frequence is considered too high, then maybe requesting a new schedule every time the SoC changes is not a good choice?

Could be because you have a smaller battery and therefore charge relatively quick?
The higher update frequency is not a problem I think, specifically when hosting FM locally.
The SoC change is a relevant trigger though because it is of impact on the schedule.
